config/routes.rb
Rails.application.routes.draw do
  resources :destinations

  root 'welcome#index'

  get 'about' => 'welcome#about'

  get 'contact' => 'welcome#contact'

  get 'activities' => 'welcome#activities'

end

app/models/destination.rb
class Destination < ActiveRecord::Base

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
      if params[:country] == nil
        @destinations = Destination.all
      else
        @destinations = Destination.where(country: params[:country].titleize)
      end

      @my_countries = Destination.select(:country).distinct

  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params)

    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:city, :country, :description, :population, :avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@homeland = "Italy"
  	@countries = ['Norway', 'Sweeden', 'Peru']
  end

  def about
  	@pics = ["Peru.jpeg", "peru-flag.gif", "peru-map.gif", "police.jpg"]
  	@color = params[:color]
  	@size = params[:size]
  end

 def contact
  	@color = params[:color]
  end

   def activities
  	@pics = ["Peru.jpeg", "peru-flag.gif", "peru-map.gif", "police.jpg"]
  	@pics.shuffle!
  	@color = params[:color]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination) do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :country %><br>
    <%= f.text_field :country, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :population %><br>
    <%= f.number_field :population, class:"form-control" %>
  </div>

   <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form' %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Destinations</h1>

<ul class="nav nav-pills" role="tablist">
  <li><%= link_to "All", destinations_path %></li>
   <% @my_countries.each do |c| %>
        <li><%= link_to "#{c.country}", controller: "destinations", country:"#{c.country}" %></li> 
      <% end %>
</ul>

  <div class="row">
    <% @destinations.each do |destination| %>
      <div class="col-md-4">
        <div class="panel panel-warning">
          <div class="panel-body">
            <h2><%= destination.city %></h2>
            <h3><%= destination.country %></h3>
            <p><%= destination.population %></p>
            <% if destination.avatar_file_name != nil %>
              <%= image_tag destination.avatar.url(:medium), class:"img-responsive" %>
              <% end %>
            <p><%= destination.description %></p>
            <div class="btn-group">
              <%= link_to 'Show', destination, class:"btn btn-default" %>
              <%= link_to 'Edit', edit_destination_path(destination), class:"btn btn-default"  %>
              <%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-default" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<br>

<%= link_to 'New Destination', new_destination_path, class:"btn btn-default"  %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @destination.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @destination.population %>
</p>

<p>
  <strong>Population:</strong>
  <%= @destination.country %>
</p>

<%= image_tag @destination.avatar.url %>

<p>
  <strong>Description:</strong>
  <%= @destination.description %>
</p>


<div class="btn-group">
	<%= link_to 'Edit', edit_destination_path(@destination), class:"btn btn-default" %> |
	<%= link_to 'Back', destinations_path, class:"btn btn-default"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Travel</title>

  	<!-- google fonts -->
	<%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Indie+Flower' %>


	<!-- Latest compiled and minified CSS -->
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>

	<!-- Latest compiled and minified JavaScript -->
	<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
  		<div class="container-fluid">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= link_to "Travel", root_path, class:"navbar-brand" %>
		    </div>

			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul class="nav navbar-nav">
			        <li><%= link_to "About", about_path %></li>
			        <li><%= link_to "Contact", contact_path %></li>
			        <li><%= link_to "Activities", activities_path %></li>
			        <li><%= link_to "Destinations", destinations_path %></li>
			        <!-- <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="#">Action</a></li>
			            <li><a href="#">Another action</a></li>
			            <li><a href="#">Something else here</a></li>
			            <li class="divider"></li>
			            <li><a href="#">Separated link</a></li>
			            <li class="divider"></li>
			            <li><a href="#">One more separated link</a></li>
			          </ul>
			        </li> -->
			      </ul>
			    </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/welcome/about.html.erb
<style>
	body {

		background: <%= @color %>;

	}
</style>

<h1>About my travel site</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<ul>
	<% @pics.each do |pics| %>
		<li><%= image_tag pics %></li> 
	<% end %>
</ul>

<p>My totes fav color is <%= @color %>. DUH.</p>

<% if @size.to_i <= 12 %>
	<p> Your tiny shoes are only size <%= @size %> ? </p>
	<% else %>
	<p> Damn BigFoot! You have a size <%= @size %> ? </p>
<% end %>

app/views/welcome/activities.html.erb
<!-- kangaroo.html.erb -->

<style>
	p, h1 {
		color: <%= @color %>;;

	}

</style>

<h1>Activities !!! </h1>

<p>Check out these random activities.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<%= link_to "Blue", {controller: "welcome", action: "activities", color: "blue"}, class: "btn btn-primary" %>
<%= link_to "Red", {controller: "welcome", action: "activities", color: "red"}, class: "btn btn-danger" %>
<%= link_to "Orange", {controller: "welcome", action: "activities", color: "orange"}, class: "btn btn-primary" %>
<%= link_to "Purple", {controller: "welcome", action: "activities", color: "purple"}, class: "btn btn-danger" %>

<ul>
	<% @pics.each do |pics| %>
		<li><%= image_tag pics %></li> 
	<% end %>
</ul>

app/views/welcome/contact.html.erb
<!-- contact.html.erb -->
<style>
	body {

		background: <%= @color %>;
	}
</style>


<%= link_to "Blue", {controller: "welcome", action: "contact", color: "blue"}, class: "btn btn-primary" %>
<%= link_to "Red", {controller: "welcome", action: "contact", color: "red"}, class: "btn btn-danger" %>

<p>Contact me @thomasweld on Twitter!</p>

app/views/welcome/index.html.erb
<h1>Welcome YO ! </h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>My name is Thomas and my family is from <%= @homeland %></p>

<p>My name is Thomas and my family is from <%= @countries %></p>


<ul>
	<% @countries.each do |country| %>
		<li><%= country %></li> 
	<% end %>
</ul>

<%= image_tag "Peru.jpeg", alt: "Peru", id: "pr", class: "img-responsive" %>
<%= image_tag "peru-flag.gif", alt: "Peru", id: "pr", class: "img-responsive" %>
<%= image_tag "peru-map.gif", alt: "Peru", id: "pr", class: "img-responsive" %>
<%= image_tag "police.jpg", alt: "Peru", id: "pr", class: "img-responsive" %>